### ISSUE TITLE
How to contribute with more languages (and maybe some coding?)

### ISSUE THREAD

**Issue by raphipod** [xraymemory/bookstory-en#1]
First of all, thank you @xraymemory for doing all the hard work to translate this game into English.
I really want this project to grow (as I am a big fan of Kairosoft games) and I can work on the German translations for the game.
Maybe you can enlighten me on how to submit translations for other languages, or are those changes just made with a new column in `translation.csv`?

**Comment by xraymemory** [comment]
Yes, if you want to localize to another language just add a new column like for English, e.g. DEUTSCH or even just DE. I can change the `translate.py` script to accept language params too

**Comment by raphipod** [comment]
Great! I've just forked this project, will add a new column for DE, and send a PR when ready!
Thanks for the feedback!
