### ISSUE TITLE
BookStory_en.exe detected as malicious

### ISSUE THREAD

**Issue by andy0dvlpr** [xraymemory/bookstory-en#6]
![bdagent_Ue0GkoRz9G](https://user-images.githubusercontent.com/37957771/113564166-8e3e7380-9611-11eb-90e6-8e4120326085.png)
![mbam_BxFwx8NunH](https://user-images.githubusercontent.com/37957771/113564174-90083700-9611-11eb-801d-a45baf8277ed.png)

Not accusing you or anything, just wondering whether something could be done regarding these detections

**Comment by raphipod** [comment]
Most likely a false positive. 
Hasn't done anything malicious to my PC until now and MSDefender didn't say anything either.

I generally dislike installing other Antivirus software, as they tend to eat up CPU and RAM and generally cause problems. **The pre-installed Defender** and **common sense** is the best protection someone can have.

**Comment by xraymemory** [comment]
The .exe is unsigned and doesn't have the typical metadata you'd find with a release so that might be triggering it - after all running random .exes you get on the internet is generally bad security practice :) I'm honestly not sure how code signing and all that works on the Windows platform

I've also been unable to replicate the issue on Windows 10 with MalwareBytes or Kaspersky.  Different vendors have different heuristics.

**Comment by xraymemory** [comment]
Going to close this for now, but noted as false positive data point . Will reopen if others experience it or have any suggestions.

**Comment by patrickgalbraith** [comment]
Shows as clean now https://www.virustotal.com/gui/url/75bc4ed0bf84976b258c76204c771e4fe211f28e92b3c2f331f6a0d941ac7ead/detection

**Comment by trs-eric** [comment]
> 
> 
> Shows as clean now https://www.virustotal.com/gui/url/75bc4ed0bf84976b258c76204c771e4fe211f28e92b3c2f331f6a0d941ac7ead/detection

It does not show as clean. The method you used to check the zip file did not appear to unzip the contents of the archive. Instead if you download the file from https://github.com/xraymemory/bookstory-en/releases/download/0.5/BookStory.zip and upload it directly to virustotal, then you see many hits.

https://www.virustotal.com/gui/file/e15d33f85e8ab8eb41bc7bf2f8153024632554140170456a39f217d28e19f5b4/detection
