### ISSUE TITLE
virus warning

### ISSUE THREAD

**Issue by chasire** [xraymemory/bookstory-en#8]
Windows Defender is isolating the file informing me its a trojan Program:Win32/Uwamson.A!ml, Virus Total also seem to agree:
[https://www.virustotal.com/gui/file/e15d33f85e8ab8eb41bc7bf2f8153024632554140170456a39f217d28e19f5b4/detection](url)

**Comment by raphipod** [comment]
Weird. See #6, VirusTotal says it's clean.

**Comment by Nzen** [comment]
I can download it via curl -L -O (url), but when I try to unzip the file, windows defender wakes up and quarantines the zip.

Edition	Windows 10 Home ; Version	20H2 ; OS build	19042.985 ; Security intelligence version 1.339.17114.0 @ 2021 05 30.

Windows defender says : Detected Trojan:Script/Oneeva.A!ml

**Comment by xraymemory** [comment]
I think this might be due to the exe hacking that had to be done, which seems to set off a bunch of false positives. I personally haven't seen this happen on Windows 10 for me
